version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Zip.WebAPI/Zip.WebAPI.csproj

  build:
    commands:
      - dotnet test Zip.Tests/Zip.Tests.csproj
      - dotnet build Zip.WebAPI/Zip.WebAPI.csproj

  post_build:
    commands:
      - dotnet publish -c Release -o  ~/Zip.WebAPI/Zip.WebAPI.csproj
      
artifacts:
  files:
    - ./**/*